services:
  postgres:
    image: postgres:17-alpine
    container_name: product-postgres
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - product_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d product_db"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  product_postgres_data:
